### ISSUE TITLE
paginate on motor with query

### ISSUE THREAD

**Issue by jochman** [nazmulnnb/fastapi-paginate#5]
Hi, I'm trying to paginate on motor (mongodb) with query (`find`).

But find return a cursor and not a sequence so I'm getting and error because it is not a sequence.

what should I do?

```python
async def get_scores(
    db: AsyncIOMotorCollection, since: datetime.datetime, to: datetime.datetime
):  
    p = db.find({"timestamp": {"$le": to, "$gt": since}})
    return paginate(p)
```

**Comment by nazmulnnb** [comment]
@jochman 
you can get the sequence using 
`
result_sequence = await p.to_list(length=None)
`
